version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.22
    steps:
      - checkout
      - run: go build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context:
            - cm-team-github
            - dockerhub-shared