apiVersion: batch/v1
kind: Job
metadata:
  name: endpoint-hitter
spec:
  template:
    spec:
      containers:
      - name: endpoint-hitter
        image: coco/endpoint-hitter:latest
        command: ["/endpoint-hitter"]
        env:
          - name: "TARGET_URL"
            value: "http://post-publication-combiner:8080/{uuid}"
          - name: "THROTTLE"
            value: "3"
      restartPolicy: Never
  backoffLimit: 4
